# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'week3_movie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for week3_movie
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'RxSwift'
    pod 'RxCocoa'	
    pod 'Kingfisher'
    pod 'Hero'
    pod 'Cosmos'
    pod 'TinyConstraints'
end
